### ISSUE TITLE
Add EasyRobotics

### ISSUE THREAD

**Issue by gotmachine** [KSP-CKAN/NetKAN#10003]
```yaml
spec_version: v1.27
identifier: EasyRobotics
name: EasyRobotics
abstract: >-
  Inverse kinematics controller for KSP Breaking Grounds robotic parts :
  automatically reach targets with your custom manipulators !
author:
  - Gotmachine
license: MIT
$kref: '#/ckan/github/Gotmachine/EasyRobotics'
$vref: '#/ckan/ksp-avc'
resources:
  bugtracker: https://github.com/gotmachine/EasyRobotics/issues
  homepage: https://github.com/gotmachine/EasyRobotics
  repository: https://github.com/gotmachine/EasyRobotics
tags:
  - plugin
  - control
x_via: Generated by Metadata Webtool

```
