### ISSUE TITLE
Add WaterfallExtensions

### ISSUE THREAD

**Issue by rbeap** [KSP-CKAN/NetKAN#10014]
```yaml
spec_version: v1.27
identifier: WaterfallExtensions
$kref: '#/ckan/spacedock/3604'
release_status: stable
resources:
  bugtracker: https://github.com/rbeap/WaterfallExtensions/issues
  spacedock: https://spacedock.info/mod/3604/Waterfall%20Extensions
  repository: https://github.com/rbeap/WaterfallExtensions
  x_screenshot: >-
    https://private-user-images.githubusercontent.com/170141846/331757593-dfd25df5-4616-4dad-a693-e080e38d3be1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxOTEzNTcsIm5iZiI6MTcxNjE5MTA1NywicGF0aCI6Ii8xNzAxNDE4NDYvMzMxNzU3NTkzLWRmZDI1ZGY1LTQ2MTYtNGRhZC1hNjkzLWUwODBlMzhkM2JlMS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwNzQ0MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTgyNjEyOTJmYTQ0ZWNjMDI5MTQ5YzQ1YjU3ZWUxZGYwMDEzMDRjMmY2YzZhYzk5MzVhZjM3ZDg5OGVhNTk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.b9TbDl5M5LUPfH4abqvd2KHEwTMmgFnNPvR2RcefCPQ
tags:
  - config
  - graphics
  - sound
depends:
  - name: Waterfall
  - name: ModuleManager
recommends:
  - name: KWRocketryRebalanced
  - name: NewTantaresLV
  - name: ReStock
  - name: ShuttleLiftingBodyCormorantAeronology
x_via: Generated by Metadata Webtool

```
