### ISSUE TITLE
Add WaterfallExtensions

### ISSUE THREAD

**Issue by rbeap** [KSP-CKAN/NetKAN#10018]
```yaml
spec_version: v1.27
identifier: WaterfallExtensions
name: Waterfall Extensions
abstract: Waterfall configs for mods that don't have them out of the box
author:
  - rbeap
version: 0.4.0
$kref: '#/ckan/spacedock/3604'
release_status: stable
resources:
  spacedock: https://spacedock.info/mod/3604/Waterfall%20Extensions
  repository: https://github.com/rbeap/WaterfallExtensions
  x_screenshot: >-
    https://private-user-images.githubusercontent.com/170141846/331757593-dfd25df5-4616-4dad-a693-e080e38d3be1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNzI2MTQsIm5iZiI6MTcxNjM3MjMxNCwicGF0aCI6Ii8xNzAxNDE4NDYvMzMxNzU3NTkzLWRmZDI1ZGY1LTQ2MTYtNGRhZC1hNjkzLWUwODBlMzhkM2JlMS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQxMDA1MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDA2YmMyNmZkM2UwNDE1ZTQ0MmY2ZTEyMjM5YWUyYjllNzFkNzRkNTNlMmZmM2I0ZmJkNzk2NDA4ZTc0NjdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9bLyBKyb3dGlcL4M27okKsWddkMtSbGaMTVuiuKNXCs
tags:
  - config
ksp_version: any
depends:
  - name: Waterfall
  - name: B9PartSwitch
  - name: ModuleManager
recommends:
  - name: KWRocketry-LegacyFairings
  - name: ReStock
  - name: ShuttleLiftingBodyCormorantAeronology
  - name: ShuttleLiftingBodyCormorantAeronology
  - name: NewTantaresLV
x_via: Generated by Metadata Webtool

```
