### ISSUE TITLE
[Bug]: Netkan.exe "Unexpected character encountered"

### ISSUE THREAD

**Issue by ProgrammerFailure** [KSP-CKAN/NetKAN#10032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 11

### CKAN Version

1.34.4

### Games

KSP 1

### Game Version

1.12.5

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

No

### Describe the bug

When running netkan.exe with this argument:
```
netkan.exe --verbose CargoAccelerators.netkan
```

And this .netkan

```
spec_version: v1.27
identifier: CargoAccelerators
name: Cargo accelerators
abstract: Parts to accelerate vessels
author:
  - allista
version: v0.3.0.1
$kref: '#/ckan/github/allista/CargoAccelerators'
$vref: '#/ckan/ksp-avc'
resources:
  bugtracker: https://github.com/allista/CargoAccelerators/Issues
  homepage: https://github.com/allista/CargoAccelerators
  repository: https://github.com/allista/CargoAccelerators
tags:
  - parts
install:
  - file: GameData/CargoAccelerators
    install_to: GameData
ksp_version_min: 1.7.1
ksp_version_max: 1.12.99999
x_via: Generated by Metadata Webtool

```

It throws this error

```
Unexpected character encountered while parsing value: s. Path '', line 0, position 0.
```

I think it should have processed and made a .ckan. Couldn't find the documentation for this error.

### Steps to reproduce

Use netkan.exe
Run with --verbose flag (or don't, it happens either way)
Try to process the above .netkan
