### ISSUE TITLE
Add RSS-Origin

### ISSUE THREAD

**Issue by CharonSSS** [KSP-CKAN/NetKAN#10126]
```yaml
spec_version: v1.27
identifier: RSS-OriginGalaxyTex64k
name: RSS-Origin GalaxyTex64k
abstract: >-
  A part of RSS-Origin, which replaces your skybox with a high-quality Milky Way
  background. This is the 64k res version
author:
  - Charon_S
license: CC-BY-NC-SA-4.0
download: >-
  https://github.com/CharonSSS/RSS-Origin/releases/download/v1.1.0/RSS-Origin.GalaxyTex64k.zip
version: v1.1.0
$kref: >-
  #/ckan/github/CharonSSS/https://github.com/CharonSSS/RSS-Origin/releases/tag/v1.1.0/asset_match/RSS-Origin.GalaxyTex64k.zip
$vref: '#/ckan/ksp-avc'
resources:
  bugtracker: https://github.com/CharonSSS/RSS-Origin/issues
  license: https://github.com/CharonSSS/RSS-Origin/blob/main/LICENSE.md
  manual: https://github.com/CharonSSS/RSS-Origin#installation-guide
  homepage: https://forum.kerbalspaceprogram.com/topic/223574-*
  repository: https://github.com/CharonSSS/RSS-Origin
tags:
  - planet-pack
  - graphics
ksp_version_min: 1.12.0
ksp_version_max: 1.12.99
depends:
  - name: TextureReplacer
x_via: Generated by Metadata Webtool

```
