### ISSUE TITLE
Add RSSOriginCelestialsPackCore

### ISSUE THREAD

**Issue by CharonSSS** [KSP-CKAN/NetKAN#10121]
```yaml
spec_version: v1.27
identifier: RSSOriginCelestialsPackCore
name: RSS-Origin CelestialsPack Core
abstract: >-
  The major part of RSS-Origin, which adds plenty of asteroids, asteroid moons,
  comets, moons of gas/ice giants, dwarf planets, dwarf planet moons, and
  interstellar objects into real solar system, currently 198 in total. (dozens
  more in the future). This is the core pack
author:
  - Charon_S
license: CC-BY-NC-SA-4.0
download: >-
  https://github.com/CharonSSS/RSS-Origin/releases/download/v1.1.0/RSS-Origin.CelestialsPack.Core.zip
version: v1.1.0
$kref: >-
  #/ckan/github/CharonSSS/https://github.com/CharonSSS/RSS-Origin/releases/tag/v1.1.0/asset_match/RSS-Origin.CelestialsPack.Core.zip
$vref: '#/ckan/ksp-avc'
resources:
  bugtracker: https://github.com/CharonSSS/RSS-Origin/issues
  license: https://github.com/CharonSSS/RSS-Origin/blob/main/LICENSE.md
  manual: https://github.com/CharonSSS/RSS-Origin#installation-guide
  homepage: https://forum.kerbalspaceprogram.com/topic/223574-*
  repository: https://github.com/CharonSSS/RSS-Origin
tags:
  - planet-pack
ksp_version_min: 1.12.0
ksp_version_max: 1.12.99
depends:
  - name: RealSolarSystem
  - name: VertexMitchellNetravaliHeightMap
recommends:
  - name: TooManyOrbits
x_via: Generated by Metadata Webtool

```
