### ISSUE TITLE
Add Deferred

### ISSUE THREAD

**Issue by LGhassen** [KSP-CKAN/NetKAN#10147]
```yaml
spec_version: v1.27
identifier: Deferred
abstract: Adds deferred rendering, improves shading and performance
author:
  - Blackrack
license: GPL-3.0
download: https://github.com/LGhassen/Deferred/releases
$kref: '#/ckan/github/LGhassen/Deferred'
release_status: stable
resources:
  bugtracker: https://github.com/LGhassen/Deferred/issues
  license: https://github.com/LGhassen/Deferred/blob/master/License.md
  manual: https://github.com/LGhassen/Deferred/blob/master/Readme.md
  homepage: https://www.patreon.com/posts/deferred-106557481
  repository: https://github.com/LGhassen/Deferred
  x_screenshot: https://i.imgur.com/kraUQIz.png
tags:
  - plugin
  - graphics
ksp_version_min: 1.12.0
depends:
  - name: Shabby
  - name: Harmony2
x_via: Generated by Metadata Webtool

```
