### ISSUE TITLE
Add rss-origin-less-primary

### ISSUE THREAD

**Issue by Qazerowl** [KSP-CKAN/NetKAN#10254]
- <https://github.com/Qazerowl/RSS-Origin-Less>

```yaml
identifier: rss-origin-less-primary
name: RSS-Origin Less - Primary
abstract: >-
  A paired-down version of CharonSSS's amazing RSS-Origin Celestial Pack. Adds
  only the "best" 26 bodies instead of the full pack's 189 additions. I would
  not recommend installing any of the original "RSS-Origin CelestialsPacks"
  packages in addition to this one due to overlap.
author:
  - Qazerowl
  - CharonSSS
$kref: '#/ckan/github/Qazerowl/RSS-Origin-Less/asset_match/Primary'
tags:
  - config
  - planet-pack
ksp_version_min: 1.12.0
depends:
  - name: RSSOrigin
  - name: ModuleManager
suggests:
  - name: rss-origin-less-secondary
x_via: Generated by Metadata Webtool

```

**Comment by Qazerowl** [comment]
rss-origin-less-secondary submitted on #10255

**Comment by Qazerowl** [comment]
I generated this with the metadata webtool but it looks like it needs the following lines appended to be processed by netkan correctly:

```
spec_version: v1.31
license: CC-BY-NC-SA
install:
  - find: RSSOrigin
    install_to: GameData
```
