### ISSUE TITLE
Add rss-origin-less-secondary

### ISSUE THREAD

**Issue by Qazerowl** [KSP-CKAN/NetKAN#10255]
- <https://github.com/Qazerowl/RSS-Origin-Less>

```yaml
identifier: rss-origin-less-secondary
name: RSS-Origin Less - Secondary
abstract: >-
  A paired-down version of CharonSSS's amazing RSS-Origin Celestial Pack.
  Combined with my "RSS-Origin Less - Primary", these two packs add 78 bodies
  instead of the full pack's 189 additions. "RSS-Origin Less - Primary" is
  STRONGLY recommended. I would not recommend installing any of the original
  "RSS-Origin CelestialsPacks" packages in addition to this one due to overlap.
author:
  - Qazerowl
  - CharonSSS
$kref: '#/ckan/github/Qazerowl/RSS-Origin-Less/asset_match/Secondary'
tags:
  - config
  - planet-pack
ksp_version_min: 1.12.0
depends:
  - name: RSSOrigin
  - name: ModuleManager
recommends:
  - name: rss-origin-less-primary
x_via: Generated by Metadata Webtool
```

**Comment by Qazerowl** [comment]
rss-origin-less-primary submitted on #10254

**Comment by Qazerowl** [comment]
I generated this with the metadata webtool but it looks like it needs the following lines appended to be processed by netkan correctly:

```
spec_version: v1.31
license: CC-BY-NC-SA
install:
  - find: RSSOrigin
    install_to: GameData
```
