### ISSUE TITLE
Add OCCULT

### ISSUE THREAD

**Issue by aspctt** [KSP-CKAN/NetKAN#10296]
- <https://github.com/aspctt/OCCULT>

```yaml
identifier: OCCULT
name: OCCULT - Patch Compendium
abstract: A collection of different patches that bring balancing/QoL changes. Choose which pathces you want via PatchManager!
author:
  - aspctt
license: GPL-3.0
$kref: '#/ckan/github/aspctt/OCCULT'
$vref: '#/ckan/ksp-avc'
release_status: stable
resources:
  license: https://raw.githubusercontent.com/aspctt/OCCULT/refs/heads/main/LICENSE
  homepage: https://github.com/aspctt/OCCULT
  repository: https://github.com/aspctt/OCCULT
tags:
  - config
  - convenience
  - planet-pack
  - graphics
ksp_version: any
depends:
  - name: PatchManager
supports:
  - name: Scatterer
  - name: JX2Antenna
  - name: NearFutureLaunchVehicles
  - name: SystemHeat-FissionEngines
x_via: Generated by Metadata Webtool
```
