### ISSUE TITLE
Update BLEAK metadata

### ISSUE THREAD

**Issue by aspctt** [KSP-CKAN/NetKAN#10297]
```yaml
identifier: BLEAK
name: BLEAK - TUFX Profiles
abstract: A nice-looking set of TUFX profiles
author:
  - aspctt
license: GPL-3.0
$kref: '#/ckan/github/aspctt/BLEAK'
$vref: '#/ckan/ksp-avc'
release_status: stable
resources:
  license: https://raw.githubusercontent.com/aspctt/BLEAK/refs/heads/main/LICENSE
  homepage: https://github.com/aspctt/BLEAK
  repository: https://github.com/aspctt/BLEAK
tags:
  - config
  - graphics
ksp_version: any
depends:
  - name: TUFX
x_via: Generated by Metadata Webtool

```
