### ISSUE TITLE
Add LagrangeProjectRSS

### ISSUE THREAD

**Issue by dongk99** [KSP-CKAN/NetKAN#10315]
```yaml
identifier: LagrangeProjectRSS
$kref: '#/ckan/github/dongk99/LagrangeProjectRSS'
$vref: '#/ckan/ksp-avc'
resources:
  bugtracker: https://github.com/dongk99/LagrangeProjectRSS/issues
  license: https://github.com/dongk99/LagrangeProjectRSS/blob/main/LICENSE
  manual: https://github.com/dongk99/LagrangeProjectRSS/blob/main/README.md
  homepage: https://forum.kerbalspaceprogram.com/topic/226357-lagrangeproject-rss/
  repository: https://github.com/dongk99/LagrangeProjectRSS
tags:
  - physics
  - config
  - planet-pack
install:
  - file: LagrangeProjectRSS/
    install_to: GameData
ksp_version_min: 1.12.0
ksp_version_max: 1.12.99
x_via: Generated by Metadata Webtool

```
