### ISSUE TITLE
Add vtacFlagPack

### ISSUE THREAD

**Issue by sigvaldr** [KSP-CKAN/NetKAN#10370]
- <https://github.com/Viking-Tactical/KSPFlagPack>

```yaml
identifier: vtacFlagPAck
name: VTAC Flag Pack
abstract: A VikingTactical themed flag pack
author:
  - Sigvaldr
license: GPL-3.0
$kref: '#/ckan/github/Viking-Tactical/KSPFlagPack'
resources:
  bugtracker: https://github.com/Viking-Tactical/KSPFlagPack/issues
  homepage: https://github.com/Viking-Tactical/KSPFlagPack
  repository: https://github.com/Viking-Tactical/KSPFlagPack
ksp_version: any
x_via: Generated by Metadata Webtool

```
