### ISSUE TITLE
Add OPXFinalFrontierRibbons

### ISSUE THREAD

**Issue by arbsoup** [KSP-CKAN/NetKAN#10548]
- <https://github.com/arbsoup/OPXFinalFrontierRibbons>
- <https://forum.kerbalspaceprogram.com/topic/227896-*>

```yaml
identifier: OPXFinalFrontierRibbons
name: OPX Final Frontier Ribbons
license: CC-BY-NC-4.0
$kref: '#/ckan/github/arbsoup/OPXFinalFrontierRibbons'
release_status: stable
resources:
  license: https://github.com/arbsoup/OPXFinalFrontierRibbons/blob/main/LICENSE.md
  manual: https://github.com/arbsoup/OPXFinalFrontierRibbons/blob/main/README.md
  homepage: https://forum.kerbalspaceprogram.com/topic/227896-*
tags:
  - config
  - crewed
install:
  - file: OPXFinalFrontierRibbons/
    install_to: GameData
ksp_version: 1.12.5
depends:
  - name: FinalFrontier
supports:
  - name: OPX-JoolPlus
  - name: OPX-SarnusPlus
  - name: OPX-UrlumPlus
  - name: NeidonPlus
x_via: Generated by Metadata Webtool

```
