### ISSUE TITLE
Add Coatl-Aerospace-Redux

### ISSUE THREAD

**Issue by PadroneSF** [KSP-CKAN/NetKAN#10558]
```yaml
identifier: Coatl-Aerospace-Redux
$kref: '#/ckan/github/PadroneSF/Coatl-Aerospace-Redux'
$vref: '#/ckan/ksp-avc'
release_status: testing
resources:
  bugtracker: https://github.com/PadroneSF/Coatl-Aerospace-Redux/issues
  homepage: >-
    https://forum.kerbalspaceprogram.com/topic/227937-coatl-aerospace-redux-v01800-05192025/
  repository: https://github.com/PadroneSF/Coatl-Aerospace-Redux/releases/
tags:
  - parts
  - science
  - uncrewed
install:
  - file: CoatlAerospace
    install_to: GameData
ksp_version: 1.12.5
depends:
  - name: B9PartSwitch
  - name: FirespitterCore
  - name: DMagicScienceAnimate
  - name: ModuleManager
recommends:
  - name: DMagicOrbitalScience
  - name: SCANsat
x_via: Generated by Metadata Webtool

```
