### ISSUE TITLE
Add Headlines

### ISSUE THREAD

**Issue by bongotastic** [KSP-CKAN/NetKAN#8745]
```yaml
spec_version: v1.16
identifier: Headlines
$kref: '#/ckan/github/bongotastic/Headlines'
release_status: development
resources:
  bugtracker: https://github.com/bongotastic/Headlines/issues
  license: https://github.com/bongotastic/Headlines/blob/master/LICENSE.md
  manual: https://github.com/bongotastic/Headlines/wiki
  homepage: >-
    https://forum.kerbalspaceprogram.com/index.php?/topic/204561-110-headlines-v03-beta-reputation-and-crewmember-careers-for-rp1-august-28th-2021/
  repository: https://github.com/bongotastic/Headlines
ksp_version: 1.10.1
depends:
  - name: RP-0
recommends:
  - name: KerbalRenamer
x_via: Generated by Metadata Webtool

```
