### ISSUE TITLE
Add Headlines

### ISSUE THREAD

**Issue by bongotastic** [KSP-CKAN/NetKAN#8771]
```yaml
spec_version: v1.16
identifier: Headlines
license: CC-BY-NC-4.0
$kref: '#/ckan/github/bongotastic/Headlines'
resources:
  license: https://github.com/bongotastic/Headlines/blob/master/LICENSE.md
  manual: https://github.com/bongotastic/Headlines/wiki
  homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/204561-*
ksp_version_min: '1.8'
ksp_version_max: 1.10.1
depends:
  - name: RP-0
  - name: KerbalRenamer
    min_version: '1.5'
  - name: KerbalAlarmClock
x_via: Generated by Metadata Webtool

```
