### ISSUE TITLE
New mod : OreToParts

### ISSUE THREAD

**Issue by Goufalite** [KSP-CKAN/NetKAN#8781]
Hello,

Please find a request for adding my mod OreToParts to CKAN

Thanks!

```yaml
spec_version: 1
identifier: OreToParts
name: Ore To Parts
abstract: >-
  Transforms ore tanks into ore to part converters, part duplicators or ore to
  EVA fuel converters.
author:
  - Goufalite
license: CC-BY-SA-4.0
version: 0.3.1.0
$kref: '#/ckan/github/Goufalite/OreToParts/asset_match/OreToParts-'
resources:
  license: https://creativecommons.org/licenses/by-sa/4.0/
  manual: https://github.com/Goufalite/OreToParts/wiki
  homepage: >-
    https://forum.kerbalspaceprogram.com/index.php?/topic/203705-11121121ore-to-parts-craft-parts-with-ore-duplicate-parts/
  x_screenshot: https://imgur.com/I5dEh7a.png
ksp_version_min: 1.11.2
depends:
  - name: ModuleManager
x_via: Generated by Metadata Webtool

```
