### ISSUE TITLE
[Mod] Add AdjustmentTool

### ISSUE THREAD

**Issue by ktchen14** [KSP-CKAN/NetKAN#8952]
```yaml
spec_version: 1
identifier: AdjustmentTool
$kref: '#/ckan/github/ktchen14/AdjustmentTool'
ksp_version_min: 1.12.2
x_via: Generated by Metadata Webtool
```
