### ISSUE TITLE
Add SpaceDustUnbound V 1.0.2 (More info, recommendations fix)

### ISSUE THREAD

**Issue by Vexxel** [KSP-CKAN/NetKAN#9117]
```yaml
spec_version: 1
identifier: SpaceDustUnbound
name: Space Dust Unbound
abstract: >-
  Adds Space Dust bands for popular Community Resource Pack resources to
  celestial bodies from the stock game, Galaxies Unbound systems and the Outer
  Planets Mod
author:
  - Vexxel
license: MIT
download: >-
  https://github.com/Vexxel/SpaceDustUnbound/releases/download/v1.0.2/SpaceDustUnbound.v1.0.2.zip
version: 1.0.2
$kref: '#/ckan/github/Vexxel/SpaceDustUnbound'
release_status: stable
resources:
  bugtracker: https://github.com/Vexxel/SpaceDustUnbound/issues
  license: https://github.com/Vexxel/SpaceDustUnbound/blob/main/LICENSE
  spacedock: https://spacedock.info/mod/2970/SpaceDustUnbound
  homepage: https://spacedock.info/mod/2970/SpaceDustUnbound
  repository: https://github.com/Vexxel/SpaceDustUnbound
  x_screenshot: >-
    https://spacedock.info/content/Vexxel_76203/SpaceDustUnbound/SpaceDustUnbound-1643969459.png
ksp_version_min: '1.11'
depends:
  - name: CommunityResourcePack
  - name: SpaceDust
  - name: ModuleManager
recommends:
  - name: OuterPlanetsMod
  - name: GalaxiesUnbound-Core
suggests:
  - name: Blueshift
x_via: Generated by Metadata Webtool

```
