### ISSUE TITLE
Add NeistAir Reupdated

### ISSUE THREAD

**Issue by jdopss** [KSP-CKAN/NetKAN#9163]
```yaml
spec_version: v1.16
identifier: NeistAir
name: NeistAir Reupdated
author:
  - KerbMario
version: P9
$kref: '#/ckan/spacedock/3034'
install:
  - file: ''
    install_to: GameData
ksp_version_min: '1.10'
recommends:
  - name: FilterExtensions
x_via: Generated by Metadata Webtool

```
