### ISSUE TITLE
Add KSAIVAUpgrade

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-CKAN/NetKAN#9172]
```yaml
spec_version: v1.16
identifier: KSAIVAUpgrade
name: KSA IVA Upgrade
abstract: Detailed IVAs for the stock mk1 pods and cockpits.
author:
  - RangeMachine
  - JonnyOThan
license: CC-BY-SA-2.0
download: https://github.com/JonnyOThan/KSA-IVA-Upgrade/releases
version: 1.5.0
$kref: '#/ckan/spacedock/211'
$vref: '#/ckan/ksp-avc'
resources:
  bugtracker: https://github.com/JonnyOThan/KSA-IVA-Upgrade/issues
  license: https://github.com/JonnyOThan/KSA-IVA-Upgrade/blob/main/LICENSE
  homepage: >-
    https://forum.kerbalspaceprogram.com/index.php?/topic/208598-ksa-iva-upgrade-adopted-mk1-stock-parts/
  repository: https://github.com/JonnyOThan/KSA-IVA-Upgrade
  x_screenshot: https://i.imgur.com/MkfyOsO.png
ksp_version_min: '1.5'
depends:
  - name: RasterPropMonitor
  - name: ASETProps
  - name: ASETAvionics
  - name: ModuleManager
recommends:
  - name: Reviva
suggests:
  - name: DockingPortAlignmentIndicator
  - name: SCANsat
  - name: Astrogator
  - name: HullcamVDSContinued
x_via: Generated by Metadata Webtool

```
