### ISSUE TITLE
Add RFA-One

### ISSUE THREAD

**Issue by RFA-One** [KSP-CKAN/NetKAN#9174]
```yaml
spec_version: v1.25
identifier: RFA-One
name: RFA One
abstract: Adds parts to build Rocket Factory Agusburg's premier smallsat launcher
author:
  - Rocket Factory Augsburg
license: CC-BY-NC-SA-4.0
version: '1.0'
$kref: '#/ckan/spacedock/3044'
install:
  - file: Kerbal Space Program/GameData/
    install_to: GameData
  - file: Kerbal Space Program/Ships/
    install_to: Ships
  - file: Kerbal Space Program/saves/scenarios/
    install_to: Scenarios
  - file: Kerbal Space Program/Missions/
    install_to: Missions
ksp_version: '1.12'
ksp_version_strict: true
x_via: Generated by Metadata Webtool

```
