### ISSUE TITLE
Add KerbalWindContinued

### ISSUE THREAD

**Issue by RCrockford** [KSP-CKAN/NetKAN#9307]
```yaml
spec_version: v1.16
identifier: KerbalWindContinued
$kref: '#/ckan/github/RCrockford/KerbalWind'
$vref: '#/ckan/ksp-avc'
ksp_version_min: 1.12.3
depends:
  - name: FerramAerospaceResearch
x_via: Generated by Metadata Webtool

```
