### ISSUE TITLE
Add Kerbal-Kountries

### ISSUE THREAD

**Issue by CTD37** [KSP-CKAN/NetKAN#9338]
```yaml
spec_version: 1
identifier: Kerbal-Kountries
name: Kerbal Kountries
abstract: Adds kerbalized country and agency flags
author:
  - Delta37
version: '1.0'
$kref: '#/ckan/github/CTD37/Kerbal-Kountries'
resources:
  homepage: >-
    https://forum.kerbalspaceprogram.com/index.php?/topic/209768-kerbal-kountries-kerbalized-nations-and-agencies/
ksp_version: any
x_via: Generated by Metadata Webtool
```

- https://github.com/CTD37/Kerbal-Kountries
- https://forum.kerbalspaceprogram.com/index.php?/topic/209768-kerbal-kountries-kerbalized-nations-and-agencies/
