### ISSUE TITLE
TUFX 1.0.5 is not compatible with older KSP versions

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-CKAN/NetKAN#9368]
```yaml
spec_version: v1.16
identifier: TUFX
name: TUFX
abstract: Post-processing FX for KSP
author:
  - shadowmage45,JonnyOThan
license: GPL-3.0
download: >-
  https://github.com/shadowmage45/TUFX/releases/download/1.0.5.0/TUFX-1.0.5.0.zip
version: 1.0.5.0
$vref: '#/ckan/ksp-avc'
resources:
  bugtracker: https://github.com/shadowmage45/TUFX/issues
  homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/192212-*
  repository: https://github.com/shadowmage45/TUFX
ksp_version_min: '1.12'
depends:
  - name: ModuleManager
x_via: Generated by Metadata Webtool

```
