### ISSUE TITLE
Add SkyhawkScienceSystem

### ISSUE THREAD

**Issue by Qazerowl** [KSP-CKAN/NetKAN#9377]
- https://github.com/CessnaSkyhawk/SkyhawkScienceSystem
- <https://forum.kerbalspaceprogram.com/index.php?/topic/206109-*>

```yaml
spec_version: v1.16
identifier: SkyhawkScienceSystem
$kref: >-
  #/ckan/github/CessnaSkyhawk/SkyhawkScienceSystem/asset_match/SkyhawkScienceSystem
release_status: stable
resources:
  license: https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode
  manual: https://github.com/CessnaSkyhawk/SkyhawkScienceSystem/wiki
  homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/206109-*
ksp_version: 1.12.3
depends:
  - name: B9PartSwitch
  - name: BluedogDB
  - name: CommunityResourcePack
  - name: ModuleManager
recommends:
  - name: CryoTanks-Core
  - name: Kopernicus
  - name: RationalResources
  - name: RationalResourcesNuclearFamily
  - name: RationalResourcesParts
suggests:
  - name: SkyhawkKerbalism
  - name: ProbesPlus
  - name: ExplodiumBreathingEngines
  - name: SpecialDelivery
  - name: TundraExploration
  - name: AirplanePlus
  - name: CryoEngines
  - name: FarFutureTechnologies
  - name: HeatControl
  - name: KerbalAtomics
  - name: KerbalPlanetaryBaseSystems
  - name: SpaceXLegs
  - name: MissingHistory
  - name: MK1StkOpenCockpit
  - name: Mk2Expansion
  - name: Mk3Expansion
  - name: NearFutureAeronautics
  - name: NearFutureConstruction
  - name: NearFutureElectrical
  - name: NearFutureExploration
  - name: NearFutureLaunchVehicles
  - name: NearFuturePropulsion
  - name: NearFutureSolar
  - name: NearFutureSpacecraft
  - name: PlanetsideExplorationTechnologies
  - name: ReStock
  - name: ReStockPlus
  - name: StockalikeMiningExtension
  - name: StationPartsExpansionRedux
  - name: TundraTechnologies
x_via: Generated by Metadata Webtool

```
