### ISSUE TITLE
Add SkyhawkKerbalism

### ISSUE THREAD

**Issue by Qazerowl** [KSP-CKAN/NetKAN#9378]
- https://github.com/CessnaSkyhawk/SkyhawkKerbalism
- https://forum.kerbalspaceprogram.com/index.php?/topic/206109-*

```yaml
spec_version: v1.16
identifier: SkyhawkKerbalism
$kref: '#/ckan/github/CessnaSkyhawk/SkyhawkKerbalism/asset_match/SkyhawkKerbalism\-'
release_status: stable
resources:
  license: https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode
  homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/206109-*
ksp_version: 1.12.3
provides:
  - Kerbalism-Config
conflicts:
  - name: Kerbalism-Config
depends:
  - name: SkyhawkScienceSystem
  - name: B9PartSwitch
  - name: Kerbalism
x_via: Generated by Metadata Webtool

```
