### ISSUE TITLE
Add SIMPLEXResources

### ISSUE THREAD

**Issue by Qazerowl** [KSP-CKAN/NetKAN#9380]
```yaml
spec_version: 1
identifier: SIMPLEXResources
$kref: '#/ckan/spacedock/2045'
release_status: stable
tags:
  - config
  - resources
recommends:
  - name: SimplexTechTree
  - name: TETRIXTechTree
  - name: SCANsat
  - name: ExtraPlanetaryLaunchpads
suggests:
  - name: KeridianDynamicsVesselAssembly
  - name: StockalikeMiningExtension
  - name: NearFutureConstruction
  - name: StationPartsExpansionRedux
  - name: SIMPLEXKerbalism
x_via: Generated by Metadata Webtool

```

Author already has other mods on CKAN, and it looks like he intended to add this mod last year but must have forgotten: https://forum.kerbalspaceprogram.com/index.php?/topic/181056-1123-and-prior-simplex-resources-112/&do=findComment&comment=4053917
