### ISSUE TITLE
Add BDA-E

### ISSUE THREAD

**Issue by SuicidalInsanity** [KSP-CKAN/NetKAN#9412]
```yaml
spec_version: v1.27
identifier: BDA-E
$kref: '#/ckan/github/BrettRyland/BDArmory-Extended'
release_status: development
resources:
  bugtracker: https://github.com/BrettRyland/BDArmory-Extended/issues
  repository: https://github.com/BrettRyland/BDArmory-Extended
tags:
  - parts
ksp_version_min: '1.9'
depends:
  - name: BDArmory
x_via: Generated by Metadata Webtool

```
