### ISSUE TITLE
Add RunwayProject

### ISSUE THREAD

**Issue by SuicidalInsanity** [KSP-CKAN/NetKAN#9457]
```yaml
spec_version: v1.27
identifier: RunwayProject
name: RWP Modpack
abstract: A modpack for Scott Manley's Runway Project
version: '1.0'
$kref: '#/ckan/spacedock/2487'
tags:
  - parts
  - plugin
  - combat
ksp_version_min: 1.12.0
depends:
  - name: ModuleManager
  - name: PhysicsRangeExtender
  - name: ModeratelyPlaneRelated
  - name: ColdWarAerospace
  - name: Mk2Expansion
  - name: Mk3Expansion
  - name: B9PartSwitch
  - name: AirplanePlus
  - name: B9-PWings-Fork
  - name: BDArmoryExtended
  - name: SmartParts
suggests:
  - name: VesselMoverContinued
x_via: Generated by Metadata Webtool

```
