### ISSUE TITLE
[Mod] BLEAK

### ISSUE THREAD

**Issue by aspctt** [KSP-CKAN/NetKAN#9458]
```yaml
spec_version: v1.27
identifier: BLEAK
name: BLEAK - TUFX Profiles
abstract: A nice-looking set of TUFX profiles
author:
  - aspct
license: GPL-3.0
version: '1.0'
$kref: '#/ckan/github/aspctt/BLEAK'
release_status: stable
resources:
  license: https://github.com/aspctt/BLEAK/blob/main/LICENSE
  repository: https://github.com/aspctt/BLEAK
tags:
  - config
  - graphics
ksp_version: any
depends:
  - name: TUFX
x_via: Generated by Metadata Webtool

```
