### ISSUE TITLE
Add FreeIva suggestions and recommendations

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-CKAN/NetKAN#9473]
```yaml
spec_version: v1.2
identifier: FreeIva
author:
  - pizzaoverhead,Icecovery,JonnyOThan
license: GPL-2.0
$kref: '#/ckan/spacedock/3151'
$vref: '#/ckan/ksp-avc'
depends:
  - name: ModuleManager
recommends:
  - name: ThroughTheEyesOfaKerbal
suggests:
  - name: Reviva
  - name: RasterPropMonitor
  - name: DE-IVAExtension
  - name: AvionicsSystems
supports:
  - name: PlanetsideExplorationTechnologies
  - name: StationPartsExpansionRedux-IVAs
  - name: Buffalo2
x_via: Generated by Metadata Webtool

```
