### ISSUE TITLE
Add RealFuelsISRU

### ISSUE THREAD

**Issue by frostbytedata** [KSP-CKAN/NetKAN#9484]
Thanks for reviewing :)

```yaml
spec_version: v1.27
identifier: RealFuelsISRU
$kref: '#/ckan/spacedock/3177'
release_status: stable
resources:
  repository: https://github.com/frostbytedata/ksp-realfuels-isru
tags:
  - parts
  - config
  - resources
depends:
  - name: RealFuels
supports:
  - name: FelineUtilityRovers
  - name: RFStockalike
x_via: Generated by Metadata Webtool

```
