### ISSUE TITLE
Add OtherWorlds

### ISSUE THREAD

**Issue by pkmniako** [KSP-CKAN/NetKAN#9555]
```yaml
spec_version: v1.27
identifier: OtherWorlds
name: Other Worlds - Story & Planet Mod
abstract: >-
  A mod with an interstellar destination and a custom and a full-fledged story
  for you to unveil
$kref: '#/ckan/github/pkmniako/OtherWorlds_Public'
release_status: stable
resources:
  license: https://github.com/pkmniako/OtherWorlds_Public/blob/main/License.txt
  homepage: https://pkmniako.github.io/OtherWorldsProgram/index.html
  x_screenshot: https://pkmniako.github.io/OtherWorldsProgram/planets/cercani.html
tags:
  - plugin
  - planet-pack
install:
  - file: OtherWorldsReboot
    install_to: GameData
ksp_version_min: '1.12'
depends:
  - name: Kopernicus
  - name: CommunityTerrainTexturePack
  - name: VertexMitchellNetravaliHeightMap
recommends:
  - name: ContractConfigurator
  - name: Scatterer
  - name: EnvironmentalVisualEnhancements
  - name: Parallax-StockTextures
  - name: KopernicusExpansionContinued-EmissiveFX
suggests:
  - name: FarFutureTechnologies
x_via: Generated by Metadata Webtool

```
