### ISSUE TITLE
Add ASETProps

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-CKAN/NetKAN#9564]
This should be taken instead of https://github.com/KSP-CKAN/NetKAN/pull/9559

```yaml
spec_version: v1.27
identifier: ASETProps
name: ASET Consolidated Props Pack
abstract: >-
  A set of interactive props for use in IVAs with RasterPropMonitor or MOARdV's
  Avionics Systems
author:
  - alexustas,Stone Blue,JonnyOThan
license: CC-BY-NC-SA-3.0
download: https://spacedock.info/mod/3240/ASET%20Consolidated%20Props%20Pack
version: 2.0.0
$kref: '#/ckan/spacedock/3240'
$vref: '#/ckan/ksp-avc'
resources:
  spacedock: https://spacedock.info/mod/3240/ASET%20Consolidated%20Props%20Pack
  homepage: >-
    https://forum.kerbalspaceprogram.com/index.php?/topic/211905-1125-181-aset-consolidated-avionics-props-iva-packs-adopted/
  repository: https://github.com/StoneBlue/ASET-Consolidated-Props
tags:
  - library
  - crewed
install:
  - file: GameData/ASET
    install_to: GameData
ksp_version_min: 1.8.1
ksp_version_max: 1.12.99
depends:
  - name: ModuleManager
  - name: ASETAgency
  - name: RasterPropMonitor-Core
supports:
  - name: MechJeb2
  - name: SCANsat
  - name: VesselView
  - name: DockingPortAlignmentIndicator
  - name: RealChute
  - name: TACLS
x_via: Generated by Metadata Webtool

```
