### ISSUE TITLE
Add ASETAgency

### ISSUE THREAD

**Issue by StoneBlue** [KSP-CKAN/NetKAN#9568]
```yaml
spec_version: v1.27
identifier: ASETAgency
name: ASET Consolidated Agency
abstract: ASET Agency and Flag
author:
  - alexustas
  - StoneBlue
license: CC-BY-NC-SA-3.0
download: https://spacedock.info/mod/3248/ASET%20Consolidated%20Agency
version: '2.0'
$vref: '#/ckan/ksp-avc'
resources:
  bugtracker: https://github.com/StoneBlue/ASET-Consolidated-Agency/issues
  spacedock: https://spacedock.info/mod/3248/ASET%20Consolidated%20Agency
  homepage: >-
    https://forum.kerbalspaceprogram.com/index.php?/topic/211905-1125-181-aset-consolidated-avionics-props-iva-packs-adopted
  repository: https://github.com/StoneBlue/ASET-Consolidated-Agency
  x_screenshot: >-
    https://spacedock.info/content/StoneBlue_14786/ASET_Consolidated_Agency/ASET_Consolidated_Agency-1676472297.png
tags:
  - library
  - agency
ksp_version_min: 1.8.1
ksp_version_max: 1.12.99
recommends:
  - name: ASETAvionics
  - name: ASETProps
x_via: Generated by Metadata Webtool

```
