### ISSUE TITLE
Add FuelMyShip

### ISSUE THREAD

**Issue by SumGuyTwitches** [KSP-CKAN/NetKAN#9592]
- <https://github.com/SumGuyTwitches/FuelMyShip>

```yaml
spec_version: v1.27
identifier: FuelMyShip
abstract: >-
  Allows you to transfer fuel from a station into a docked craft via the docking
  port.
$kref: '#/ckan/github/SumGuyTwitches/FuelMyShip'
resources:
  bugtracker: https://github.com/SumGuyTwitches/FuelMyShip/issues
  repository: https://github.com/SumGuyTwitches/FuelMyShip
tags:
  - control
  - convenience
  - resources
ksp_version_min: '1.8'
ksp_version_max: '1.12'
x_via: Generated by Metadata Webtool
```
