### ISSUE TITLE
Add HUDReplacer

### ISSUE THREAD

**Issue by UltraJohn** [KSP-CKAN/NetKAN#9651]
- <https://github.com/UltraJohn/HUDReplacer>
- <https://forum.kerbalspaceprogram.com/index.php?/topic/216056-*>

```yaml
spec_version: v1.27
identifier: HUDReplacer
$kref: '#/ckan/github/UltraJohn/HUDReplacer'
$vref: '#/ckan/ksp-avc'
resources:
  license: https://github.com/UltraJohn/HUDReplacer/blob/master/LICENSE
  manual: https://github.com/UltraJohn/HUDReplacer/blob/master/README.md
  homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/216056-*
  repository: https://github.com/UltraJohn/HUDReplacer
depends:
  - name: ModuleManager
tags:
  - plugin
  - graphics
install:
  - file: GameData/HUDReplacer/
    install_to: GameData
ksp_version_min: 1.12.0
ksp_version_max: 1.12.9
x_via: Generated by Metadata Webtool

```
