### ISSUE TITLE
Add SRCS-StageableRCS

### ISSUE THREAD

**Issue by kurgut** [KSP-CKAN/NetKAN#9682]
```yaml
spec_version: v1.27
identifier: SRCS-StageableRCS
$kref: '#/ckan/spacedock/'
$vref: '#/ckan/ksp-avc'
release_status: stable
resources:
  bugtracker: https://github.com/kurgut/SRCS-Stageable-RCS/issues
  homepage: >-
    https://forum.kerbalspaceprogram.com/index.php?/topic/176365-131-112-srcs-stageable-rcs/
  repository: https://github.com/kurgut/SRCS-Stageable-RCS
tags:
  - config
  - control
  - convenience
conflicts:
  - name: RealismOverhaul
depends:
  - name: ModuleManager
x_via: Generated by Metadata Webtool

```
