### ISSUE TITLE
Add Kesa

### ISSUE THREAD

**Issue by JiMKesa** [KSP-CKAN/NetKAN#9717]
```yaml
spec_version: v1.27
identifier: Kesa
author:
  - JiMKesa
license: MIT
$kref: '#/ckan/spacedock/3409'
release_status: stable
resources:
  spacedock: https://spacedock.info/mod/3409/Kesa
  homepage: https://kesaspace.blogspot.com/p/kesa-ksp2-mod.html
  x_screenshot: https://spacedock.info/content/jimkesa_115625/Kesa/Kesa-1688168573.jpg
tags:
  - parts
x_via: Generated by Metadata Webtool

```
