### ISSUE TITLE
Add Minor Planet Sampling

### ISSUE THREAD

**Issue by DeltaDizzy** [KSP-CKAN/NetKAN#9754]
```yaml
spec_version: v1.27
identifier: minor-planet-sampling
$kref: '#/ckan/github/DeltaDizzy/MinorPlanetSampling/asset_match/MinorPlanetSampling-*'
$vref: '#/ckan/ksp-avc'
release_status: stable
tags:
  - plugin
  - config
  - science
  - uncrewed
ksp_version_min: 1.10.0
depends:
  - name: ModuleManager
  - name: Harmony2
x_via: Generated by Metadata Webtool
```

<https://github.com/DeltaDizzy/MinorPlanetSampling>

<https://forum.kerbalspaceprogram.com/topic/218820-110-112x-minor-planet-sampling-v10-8-august-2023/>
