### ISSUE TITLE
Add CryoEnginesExtensions

### ISSUE THREAD

**Issue by Kavaeric** [KSP-CKAN/NetKAN#9780]
```yaml
spec_version: v1.27
identifier: CryoEnginesExtensions
$kref: '#/ckan/spacedock/3452'
release_status: stable
resources:
  manual: https://imgur.com/a/vOaGRWF
  x_screenshot: https://i.imgur.com/R24iPxb.jpg
tags:
  - parts
depends:
  - name: CryoEngines
  - name: ModuleManager
recommends:
  - name: Waterfall
suggests:
  - name: CommunityTechTree
  - name: RocketSoundEnhancement
  - name: RocketSoundEnhancement-Config-Default
x_via: Generated by Metadata Webtool

```
