### ISSUE TITLE
Add per-save-screenshots

### ISSUE THREAD

**Issue by DeltaDizzy** [KSP-CKAN/NetKAN#9787]
```yaml
spec_version: v1.27
identifier: per-save-screenshots
name: Per-save Screenshots
abstract: >-
  Per-save Screenshots makes it so that when you take a screenshot, it is placed
  into a folder within the game's Screenshots folder that corresponds to your
  saved game. No more melting pot of all your screenshots, letting you find the
  ones you want quicker and easier.
$kref: >-
  #/ckan/github/DeltaDizzy/PerSaveScreenshots/asset_match/PerSaveScreenshots-*.zip
tags:
  - plugin
  - convenience
ksp_version: any
x_via: Generated by Metadata Webtool

```
