### ISSUE TITLE
Add OPM-Parallax-Scatters

### ISSUE THREAD

**Issue by OneSaltyPringle** [KSP-CKAN/NetKAN#9828]
```yaml
spec_version: v1.27
identifier: OPM-Parallax-Scatters
$kref: '#/ckan/spacedock/3492'
resources:
  spacedock: >-
    https://spacedock.info/mod/3492/Outer%20Planets%20Mod%20Parallax%20with%20Scatters
tags:
  - config
  - planet-pack
  - graphics
install:
  - file: GameData/OPM_Parallax/
    install_to: GameData
conflicts:
  - name: Parallax-OuterPlanetsMod
depends:
  - name: OuterPlanetsMod
  - name: Parallax
  - name: Parallax-Textures
  - name: Parallax-Scatter-Textures
x_via: Generated by Metadata Webtool

```
