### ISSUE TITLE
Add WYG! Watch Your Gforces!

### ISSUE THREAD

**Issue by kurgut** [KSP-CKAN/NetKAN#9868]
```yaml
spec_version: v1.27
identifier: WatchyourGforces
$kref: '#/ckan/spacedock/3515'
$vref: '#/ckan/ksp-avc'
release_status: stable
resources:
  spacedock: https://spacedock.info/mod/3515/WYG!%20-%20Watch%20Your%20G-forces!
  homepage: >-
    https://forum.kerbalspaceprogram.com/topic/221046-wyg-watch-your-g-forces-ksp-112/
  repository: https://github.com/kurgut/WYG-WatchYourG-Forces-
  x_screenshot: https://imgur.com/bSTzQU3
tags:
  - physics
  - config
  - crewed
depends:
  - name: ModuleManager
recommends:
  - name: DeadlyReentry
supports:
  - name: RealSolarSystem
x_via: Generated by Metadata Webtool

```
