### ISSUE TITLE
[Mod]: RasterPropMonitor Part list and Checklist

### ISSUE THREAD

**Issue by Fedex75** [KSP-CKAN/NetKAN#9874]
### Mod Name

RasterPropMonitor Part list and Checklist

### Author(s)

Fedex75

### License

GPL-3.0

### Homepage link

https://github.com/Fedex75/RPM_Parts_Checklist/

### Download link

https://github.com/Fedex75/RPM_Parts_Checklist/releases/

**Comment by HebaruSan** [comment]
Mod analyzer output:

```yaml
spec_version: v1.18
identifier: RPM-PartsList
tags:
  - plugin
install:
  - find: RPM_Parts_Checklist
    install_to: GameData
```

Presumably we need to depend on RPM as well (at least).
