### ISSUE TITLE
Add XenonISRU

### ISSUE THREAD

**Issue by A-T-L-A-S** [KSP-CKAN/NetKAN#9906]
```yaml
spec_version: v1.27
identifier: XenonISRU
name: XenonISRU
abstract: A tiny MM patch that adds Xenon Gas to Vanilla ISRUs in Kerbal space program
author:
  - A.T.L.A.S
license: MIT
download: >-
  https://github.com/A-T-L-A-S/XenonGas-ISRU/releases/download/v.1.0/Xenon_ISRU.zip
version: '1.0'
$kref: '#/ckan/spacedock/'
release_status: stable
resources:
  homepage: https://github.com/A-T-L-A-S/XenonGas-ISRU/tree/v.1.0
  repository: https://github.com/A-T-L-A-S/XenonGas-ISRU/tree/v.1.0
tags:
  - config
  - resources
ksp_version: any
depends:
  - name: ModuleManager
x_via: Generated by Metadata Webtool

```
