### ISSUE TITLE
Add BetterRocketDesigns

### ISSUE THREAD

**Issue by Bloodsucker** [KSP-CKAN/NetKAN#9928]
BetterRocketDesign, a mod to manage your designs using drap&drop similarly to how it works with the Stock Subassemblies but much better!

<https://github.com/Bloodsucker/ksp-better-rocket-designs>

```yaml
spec_version: v1.27
identifier: BetterRocketDesign
$kref: >-
  #/ckan/github/Bloodsucker/ksp-better-rocket-designs/asset_match/BetterRocketDesigns-v\.+.zip
release_status: stable
resources:
  bugtracker: https://github.com/Bloodsucker/ksp-better-rocket-designs/issues
  license: >-
    https://github.com/Bloodsucker/ksp-better-rocket-designs/blob/develop/LICENSE
  x_screenshot: >-
    https://raw.githubusercontent.com/Bloodsucker/ksp-better-rocket-designs/develop/res/save-as.png
tags:
  - plugin
  - convenience
  - editor
ksp_version: 1.12.5
depends:
  - name: ClickThroughBlocker
x_via: Generated by Metadata Webtool

```

Hello it's my very first mod for KSP and I was wondering if you could guide me in case I did something wrong. I following the Intermediate instructions in https://github.com/KSP-CKAN/CKAN/wiki/Adding-a-mod-to-the-CKAN because I wanted the mod to retrieve the .zip files from my Github. I also don't know if it's expected from me to add a metadata file to my repository.

Ideally, I'd like for CKAN to detect any mod update automatically. It seems that spacedock requires me to manually upload the .zip files every time there is a new release which I don't want to. Is it possible to ping about a new release of the mod instead of waiting for the bot to find it?

Are Github pre-release included or only stable/final release?

Thanks.
