### ISSUE TITLE
Add KSP-AutoLoad

### ISSUE THREAD

**Issue by dazoe** [KSP-CKAN/NetKAN#9982]
<https://github.com/dazoe/KSP-AutoLoad>

```yaml
spec_version: v1.27
identifier: KSP-AutoLoad
$kref: '#/ckan/github/dazoe/KSP-AutoLoad'
tags:
  - plugin
  - convenience
ksp_version: 1.12.5
x_via: Generated by Metadata Webtool
```
