### ISSUE TITLE
Add EasyISP

### ISSUE THREAD

**Issue by Tempus-superest** [KSP-CKAN/NetKAN#9983]
```yaml
spec_version: v1.27
identifier: EasyISP
$kref: '#/ckan/github/Tempus-superest/EasyISP'
$vref: '#/ckan/ksp-avc'
release_status: stable
resources:
  bugtracker: https://github.com/Tempus-superest/EasyISP/issues
  license: https://unlicense.org
  homepage: https://github.com/Tempus-superest/EasyISP
  repository: https://github.com/Tempus-superest/EasyISP
tags:
  - physics
  - convenience
  - resources
ksp_version_min: '1.1'
ksp_version_max: 1.12.5
x_via: Generated by Metadata Webtool
```

- <https://github.com/Tempus-superest/EasyISP>
