### ISSUE TITLE
Add FlyByWireSASMode

### ISSUE THREAD

**Issue by gotmachine** [KSP-CKAN/NetKAN#9988]
```yaml
spec_version: v1.27
identifier: FlyByWireSASMode
name: FlyByWireSASMode
abstract: >-
  Adds a new "fly by wire" SAS mode. When enabled, pitch and yaw inputs don't
  control the vessel directly anymore, but instead control the position of a
  custom navball direction marker that the SAS will follow automatically.
$kref: '#/ckan/github/gotmachine/FlyByWireSASMode'
$vref: '#/ckan/ksp-avc'
resources:
  bugtracker: https://github.com/gotmachine/FlyByWireSASMode/issues
  homepage: https://github.com/gotmachine/FlyByWireSASMode
  repository: https://github.com/gotmachine/FlyByWireSASMode
tags:
  - plugin
  - control
x_via: Generated by Metadata Webtool

```
